name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies (Client)
      working-directory: ./client
      run: npm install

    - name: Build React App
      working-directory: ./client
      run: npm run build

    - name: Install dependencies (Server)
      working-directory: ./server
      run: npm install